### ISSUE TITLE
Quests should not be allowed to be submitted more than once

### ISSUE THREAD

**Issue by ProtocolPav** [ProtocolPav/everthorn.net#10]
**Is your feature request related to a problem? Please describe.**
It could be easy to miss the toast, or maybe somebody clicks multiple times on the submit button and submits more than one of the same quest

**Describe the solution you'd like**
Either:
- Automatically redirect to submit a new quest
- OR Disappear the "back" and "submit" buttons, and display a button to "Create new Quest"
- OR Redirect user to the quest manager (not yet made)

**Describe alternatives you've considered**
The user can reload the page to create a new page, but I know for mars this is not intuitive

**Additional context**

**Comment by cakePhone** [comment]
Fixed in #16
