### ISSUE TITLE
Quest Creator multiple objectives & rewards

### ISSUE THREAD

**Issue by ProtocolPav** [ProtocolPav/everthorn.net#12]
**Is your feature request related to a problem? Please describe.**
Add the option to add a "new objective" when creating the quest, as well as an option to add a new reward.

**Describe the solution you'd like**
A quest can have multiple objectives. Each objective can have multiple rewards. Each reward is tied to an objective.

Objectives have an order, perhaps allow the user to change the order via drag-n-drop at the very end?

**Describe alternatives you've considered**

**Additional context**

**Comment by cakePhone** [comment]
Done! Merged into release/2
