### ISSUE TITLE
DiscordAvatar popup displays nicer info

### ISSUE THREAD

**Issue by ProtocolPav** [ProtocolPav/everthorn.net#13]
**Is your feature request related to a problem? Please describe.**
Have it display different links to different parts of the user, like to edit their profile, to view leaderboards, and of course to log out. Maybe also display at the very bottom a button-style card that says if they are a CM if they are one.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cakePhone** [comment]
This will have to wait for release-2

**Comment by cakePhone** [comment]
Will implement a whole discord profile-like popup with our links in mind

**Comment by cakePhone** [comment]
Forgot to close this earlier, I believe it's finished
