### ISSUE TITLE
New CSS heading styles are not applied

### ISSUE THREAD

**Issue by ProtocolPav** [ProtocolPav/everthorn.net#3]
The new heading styles for `h1` and so on do not apply globally. Unsure as to why.

**Comment by cakePhone** [comment]
They do, changed some to overwrite the size as it would be weird. Not sure if that's what you're referring to. Need more details

**Comment by ProtocolPav** [comment]
Wait you're right I'm dumb. What I was referring to is on the main page the heading isn't the same and when you go on mobile it doesn't become smaller but I think that's literally just cos the md: sizing isn't implemented
